export const prompts = [
  // Love & Romance
  { category: 'Love & Romance', text: 'The coffee shop where we first met.' },
  { category: 'Love & Romance', text: 'Our favorite "cheap date" spot in the city.' },
  { category: 'Love & Romance', text: 'A rainy walk that ended in a kiss.' },
  { category: 'Love & Romance', text: 'The moment I realized I was falling in love at [Location].' },
  { category: 'Love & Romance', text: 'My most cinematic "K-Drama" moment in a Vancouver park.' },
  { category: 'Love & Romance', text: 'The breakup I had to process while riding the SkyTrain.' },
  { category: 'Love & Romance', text: 'Where we went for our first anniversary.' },
  { category: 'Love & Romance', text: 'A view of the North Shore mountains that reminds me of someone.' },
  { category: 'Love & Romance', text: "That one time we got stuck in the rain but didn't care." },
  { category: 'Love & Romance', text: 'The best place in Vancouver to watch the sunset with a crush.' },
  { category: 'Love & Romance', text: 'A "sliding doors" moment: a person I saw once and never again.' },
  { category: 'Love & Romance', text: 'The specific street corner that always reminds me of an ex.' },
  { category: 'Love & Romance', text: 'My favorite spot for a "solo date" in the city.' },
  { category: 'Love & Romance', text: 'A proposal I witnessed (or had!) in public.' },
  { category: 'Love & Romance', text: "The first place I take someone I'm trying to impress." },

  // Stranger Kindness
  { category: 'Stranger Kindness', text: 'The stranger who gave me their umbrella when it started pouring.' },
  { category: 'Stranger Kindness', text: 'A time someone helped me carry my groceries/stroller up the stairs.' },
  { category: 'Stranger Kindness', text: 'The bus driver who waited for me when they saw me running.' },
  { category: 'Stranger Kindness', text: 'A conversation I had with a stranger at a dog park.' },
  { category: 'Stranger Kindness', text: 'Someone who complimented my outfit in Gastown.' },
  { category: 'Stranger Kindness', text: 'When a stranger helped me find my way when I was lost.' },
  { category: 'Stranger Kindness', text: "The most wholesome thing I've ever seen on the 99 B-Line." },
  { category: 'Stranger Kindness', text: 'A moment of shared silence with a stranger looking at the ocean.' },
  { category: 'Stranger Kindness', text: 'Someone who paid for my coffee at a drive-thru.' },
  { category: 'Stranger Kindness', text: 'When a neighbor I didn\'t know helped me during the "Snowpocalypse."' },
  { category: 'Stranger Kindness', text: 'A small act of kindness I witnessed at a community center.' },
  { category: 'Stranger Kindness', text: 'The person who returned my lost Compass card/wallet.' },
  { category: 'Stranger Kindness', text: "A time a stranger's smile turned my bad day around." },
  { category: 'Stranger Kindness', text: 'When I helped someone who was struggling with their bags.' },
  { category: 'Stranger Kindness', text: 'A piece of advice a local elder once gave me.' },

  // Community Memories
  { category: 'Community Memories', text: 'A business that is gone now that I still think about.' },
  { category: 'Community Memories', text: 'What [Neighborhood] looked like when I first moved here.' },
  { category: 'Community Memories', text: 'My favorite memory of the PNE.' },
  { category: 'Community Memories', text: "The loudest I've ever heard Vancouver cheer." },
  { category: 'Community Memories', text: 'A festival or parade that made me feel like I belonged.' },
  { category: 'Community Memories', text: 'My first time seeing the Celebration of Light fireworks.' },
  { category: 'Community Memories', text: 'Remembering a specific mural that got painted over.' },
  { category: 'Community Memories', text: 'The smell of [Specific Area] always reminds me of my childhood.' },
  { category: 'Community Memories', text: 'My favorite "hidden gem" that isn\'t a secret anymore.' },
  { category: 'Community Memories', text: 'A memory of the 2010 Olympics (or the feeling in the streets).' },
  { category: 'Community Memories', text: 'The first concert I ever went to in the city.' },
  { category: 'Community Memories', text: 'A local "character" or legend everyone in my neighborhood knew.' },
  { category: 'Community Memories', text: 'The day I finally stopped using Google Maps to get around.' },
  { category: 'Community Memories', text: 'My favorite childhood playground in the city.' },
  { category: 'Community Memories', text: 'The moment I realized this neighborhood was "home."' },

  // Thoughts & Opinions
  { category: 'Thoughts & Opinions', text: 'Vancouver rains a lot, but it makes [Place] look beautiful.' },
  { category: 'Thoughts & Opinions', text: 'My "Grey Sky" survival strategy.' },
  { category: 'Thoughts & Opinions', text: 'The most "Vancouver" thing that has ever happened to me.' },
  { category: 'Thoughts & Opinions', text: "I feel like people undersell Vancouver's [Specific Asset]." },
  { category: 'Thoughts & Opinions', text: 'I think [Tourist Spot] is actually overhyped because...' },
  { category: 'Thoughts & Opinions', text: 'My favorite way to spend a "Main Street" Saturday.' },
  { category: 'Thoughts & Opinions', text: "The best bowl of ramen/o/sushi I've had in the city." },
  { category: 'Thoughts & Opinions', text: 'My relationship with the mountains is...' },
  { category: 'Thoughts & Opinions', text: 'Why I choose to stay here despite the cost.' },
  { category: 'Thoughts & Opinions', text: 'If Vancouver were a color, it would be...' },
  { category: 'Thoughts & Opinions', text: 'The one thing I would change about the city if I were Mayor for a day.' },
  { category: 'Thoughts & Opinions', text: 'My favorite place to go when I need to be completely alone.' },
  { category: 'Thoughts & Opinions', text: 'Vancouver is my [1st/2nd/Chosen] home.' },
  { category: 'Thoughts & Opinions', text: 'The sound of the "Noon Horn" makes me feel...' },
  { category: 'Thoughts & Opinions', text: 'My favorite thrift find in a Vancouver shop.' },

  // Arrivals & Departures
  { category: 'Arrivals & Departures', text: 'My very first day in Vancouver: I felt...' },
  { category: 'Arrivals & Departures', text: 'My first week here, I was surprised by...' },
  { category: 'Arrivals & Departures', text: 'The first year was hard, but [Experience] made it worth it.' },
  { category: 'Arrivals & Departures', text: 'Why I moved here from [Other City/Country].' },
  { category: 'Arrivals & Departures', text: 'Visiting Vancouver feels like a dream because...' },
  { category: 'Arrivals & Departures', text: 'I had to move away, and the thing I miss most is...' },
  { category: 'Arrivals & Departures', text: "I'm thinking of moving away because..." },
  { category: 'Arrivals & Departures', text: 'If I only had 24 hours left in the city, I would spend them...' },
  { category: 'Arrivals & Departures', text: 'What I told my family back home about my new life here.' },
  { category: 'Arrivals & Departures', text: 'My first time visiting a Vancouver landmark (and if it lived up to the hype).' },
  { category: 'Arrivals & Departures', text: 'To me, the "real" Vancouver is found in [Specific Spot].' },
  { category: 'Arrivals & Departures', text: "A souvenir I bought here that I'll keep forever." },
  { category: 'Arrivals & Departures', text: "I want to get to know more about the city's [Culture/History]." },
  { category: 'Arrivals & Departures', text: 'The jet lag walk: My first sunrise in the city.' },
  { category: 'Arrivals & Departures', text: "Why I'll always be a Vancouverite at heart." },

  // Confessions
  { category: 'Confessions', text: 'A secret I\'ve never told anyone about a place in Vancouver.' },
  { category: 'Confessions', text: 'The person I saw on the SkyTrain and never had the courage to talk to.' },
  { category: 'Confessions', text: 'Something I did in this city that I\'m not proud of.' },
  { category: 'Confessions', text: 'A crush I never acted on.' },
  { category: 'Confessions', text: 'The real reason I moved to Vancouver.' },

  // A Visitor's Note
  { category: "A Visitor's Note", text: 'The first thing that surprised me about Vancouver.' },
  { category: "A Visitor's Note", text: 'A local spot I stumbled upon that wasn\'t in any guidebook.' },
  { category: "A Visitor's Note", text: 'What I thought Vancouver would be like vs. what it actually is.' },
  { category: "A Visitor's Note", text: 'The most "only in Vancouver" moment I witnessed as a visitor.' },
  { category: "A Visitor's Note", text: 'A conversation with a local that changed how I saw the city.' },

  // Sparks & Musings
  { category: 'Sparks & Musings', text: 'A secret spot I hope nobody else finds.' },
  { category: 'Sparks & Musings', text: 'The best thing I ever ate at a Richmond Night Market.' },
  { category: 'Sparks & Musings', text: "An overheard conversation I'll never forget." },
  { category: 'Sparks & Musings', text: 'My favorite tree in the city.' },
  { category: 'Sparks & Musings', text: 'A photo I took that perfectly captures "Vancouver."' },
  { category: 'Sparks & Musings', text: "The most beautiful commute I've ever had." },
  { category: 'Sparks & Musings', text: 'My "rainy day" playlist is inspired by...' },
  { category: 'Sparks & Musings', text: "A confession: I've never actually been to [Popular Attraction]." },
  { category: 'Sparks & Musings', text: 'My favorite time of year in the city and why.' },
  { category: 'Sparks & Musings', text: 'Vancouver is... (finish the sentence).' },
]

export const PROMPT_CATEGORIES = [
  'Love & Romance',
  'Stranger Kindness',
  'Community Memories',
  'Thoughts & Opinions',
  'Arrivals & Departures',
  'Confessions',
  "A Visitor's Note",
  'Sparks & Musings',
]
