export const prompts = [
  // Love & Romance
  { category: 'Love & Romance', text: 'My most cinematic "K-Drama" moment in Vancouver.' },
  { category: 'Love & Romance', text: 'The specific street corner that always reminds me of an ex.' },
  { category: 'Love & Romance', text: 'A proposal I witnessed (or had!) in public.' },
  { category: 'Love & Romance', text: "The first place I take someone I'm trying to impress." },
  { category: 'Love & Romance', text: 'My favourite spot for a "solo date" in the city.' },
  { category: 'Love & Romance', text: 'The best place in Vancouver to watch the sunset with a crush.' },
  { category: 'Love & Romance', text: 'That street/place that makes falling in love so much easier.' },
  { category: 'Love & Romance', text: 'Where we went for most memorable date.' },
  { category: 'Love & Romance', text: 'Doing this in Vancouver helped me process my breakup.' },
  { category: 'Love & Romance', text: 'A "sliding doors" moment: a person I saw once and never again.' },

  // Stranger Kindness
  { category: 'Stranger Kindness', text: 'I had this conversation with a stranger once…' },
  { category: 'Stranger Kindness', text: 'A stranger that helped me…' },
  { category: 'Stranger Kindness', text: 'Someone I helped…' },
  { category: 'Stranger Kindness', text: 'I got a compliment from a stranger once…' },
  { category: 'Stranger Kindness', text: "The most wholesome thing I've ever seen on the bus/train." },
  { category: 'Stranger Kindness', text: 'A piece of advice a local elder once gave me…' },
  { category: 'Stranger Kindness', text: 'An act of kindness I witnessed…' },
  { category: 'Stranger Kindness', text: "A bus driver/city worker that I should've thanked." },

  // Community Memories
  { category: 'Community Memories', text: 'A business that is gone now that I still think about.' },
  { category: 'Community Memories', text: 'What [insert neighbourhood] looked like when I first moved here.' },
  { category: 'Community Memories', text: 'My favourite memory of this place…' },
  { category: 'Community Memories', text: "The loudest I've ever heard Vancouver cheer." },
  { category: 'Community Memories', text: 'A festival or parade that made me feel like I belonged.' },
  { category: 'Community Memories', text: 'My first time seeing the Celebration of Light fireworks.' },
  { category: 'Community Memories', text: 'The smell of [blank] always reminds me of Vancouver.' },
  { category: 'Community Memories', text: 'My favourite "hidden gem" that isn\'t a secret anymore.' },
  { category: 'Community Memories', text: 'The first concert I ever went to in the city.' },
  { category: 'Community Memories', text: 'A local "character" or legend everyone in my neighbourhood knew.' },
  { category: 'Community Memories', text: 'The moment I realized this neighbourhood was "home."' },
  { category: 'Community Memories', text: 'There was this art work in the city years ago…' },

  // Dear diary, today...
  { category: 'Dear diary, today...', text: 'I just saw/passed by this person/place…' },
  { category: 'Dear diary, today...', text: 'Something someone said to me today…' },
  { category: 'Dear diary, today...', text: 'Today my boss/co-worker told me…' },
  { category: 'Dear diary, today...', text: 'Today my family/friend told me…' },
  { category: 'Dear diary, today...', text: "I can't believe what just happened 10 mins ago…" },
  { category: 'Dear diary, today...', text: 'I hate this thing about Vancouver.' },
  { category: 'Dear diary, today...', text: 'I thought of ____ again…' },
  { category: 'Dear diary, today...', text: "If you're reading this, I'm currently sitting at [Location] and..." },
  { category: 'Dear diary, today...', text: 'The song playing in my headphones right now is...' },
  { category: 'Dear diary, today...', text: "I'm currently waiting for the [Bus/Train] and I'm thinking about..." },
  { category: 'Dear diary, today...', text: 'The weather today makes me feel like...' },
  { category: 'Dear diary, today...', text: 'I just spent my $10 on...' },
  { category: 'Dear diary, today...', text: 'A photo I took that perfectly captures "Vancouver."' },
  { category: 'Dear diary, today...', text: "An overheard conversation I'll never forget." },
  { category: 'Dear diary, today...', text: 'My commute today was [Better/Worse] than usual because...' },
  { category: 'Dear diary, today...', text: "I'm procrastinating on [Task] by writing this entry." },
  { category: 'Dear diary, today...', text: 'The best part of my shift today was...' },
  { category: 'Dear diary, today...', text: 'Why is [Street Name] always so loud/busy/quiet?' },
  { category: 'Dear diary, today...', text: 'I just discovered a new shortcut through...' },
  { category: 'Dear diary, today...', text: "I'm currently annoyed by [Specific Vancouver Quirk]." },

  // Arrivals & Departures
  { category: 'Arrivals & Departures', text: 'My very first day in Vancouver: I felt...' },
  { category: 'Arrivals & Departures', text: 'My first week here, I was surprised by...' },
  { category: 'Arrivals & Departures', text: 'The first year was hard, but [Experience] made it worth it.' },
  { category: 'Arrivals & Departures', text: 'Why I moved here from [Other City/Country].' },
  { category: 'Arrivals & Departures', text: 'Visiting Vancouver feels like a dream because...' },
  { category: 'Arrivals & Departures', text: 'I had to move away, and the thing I miss most is...' },
  { category: 'Arrivals & Departures', text: "I'm thinking of moving away because..." },
  { category: 'Arrivals & Departures', text: 'If I only had 24 hours left in the city, I would spend them...' },
  { category: 'Arrivals & Departures', text: 'What I told my family back home about my new life here.' },
  { category: 'Arrivals & Departures', text: 'My first time visiting a Vancouver landmark (and if it lived up to the hype).' },
  { category: 'Arrivals & Departures', text: 'To me, the "real" Vancouver is found in [Specific Spot].' },
  { category: 'Arrivals & Departures', text: "A souvenir I bought here that I'll keep forever." },
  { category: 'Arrivals & Departures', text: "I want to get to know more about the city's [Culture/History]." },
  { category: 'Arrivals & Departures', text: 'The jet lag walk: My first sunrise in the city.' },
  { category: 'Arrivals & Departures', text: "Why I'll always be a Vancouverite at heart." },

  // Confessions
  { category: 'Confessions', text: 'A secret I\'ve never told anyone about a place in Vancouver.' },
  { category: 'Confessions', text: 'The person I saw on the SkyTrain and never had the courage to talk to.' },
  { category: 'Confessions', text: 'Something I did in this city that I\'m not proud of.' },
  { category: 'Confessions', text: 'Something I want to tell my crush.' },
  { category: 'Confessions', text: 'How he/she/they caught my eye…' },
  { category: 'Confessions', text: 'I wish I could say this to…' },
  { category: 'Confessions', text: 'I would never admit this in public, but…' },
  { category: 'Confessions', text: 'Something I\'ve been hiding from my friends/family…' },
  { category: 'Confessions', text: 'I\'ve never actually been to [popular attraction] because…' },

  // A Visitor's Note
  { category: "A Visitor's Note", text: 'The first thing that surprised me about Vancouver.' },
  { category: "A Visitor's Note", text: 'A local spot I stumbled upon that wasn\'t in any guidebook.' },
  { category: "A Visitor's Note", text: 'What I thought Vancouver would be like vs. what it actually is.' },
  { category: "A Visitor's Note", text: 'The most "only in Vancouver" moment I witnessed as a visitor.' },
  { category: "A Visitor's Note", text: 'A conversation with a local that changed how I saw the city.' },
  { category: "A Visitor's Note", text: 'What I didn\'t like so much about Vancouver.' },
  { category: "A Visitor's Note", text: 'What I wish Vancouver would improve on.' },
  { category: "A Visitor's Note", text: 'If I could visit again, I would…' },
  { category: "A Visitor's Note", text: 'I\'ve never been here, but this place in Vancouver felt like home…' },

  // Sparks & Musings
  { category: 'Sparks & Musings', text: 'A secret spot I hope nobody else finds.' },
  { category: 'Sparks & Musings', text: 'The best thing I ever ate at Richmond/Christmas Night Market.' },
  { category: 'Sparks & Musings', text: 'My favourite tree in the city.' },
  { category: 'Sparks & Musings', text: 'My "rainy day" playlist is inspired by...' },
  { category: 'Sparks & Musings', text: 'My favourite time of year in the city and why.' },
  { category: 'Sparks & Musings', text: 'Vancouver is... (finish the sentence).' },
  { category: 'Sparks & Musings', text: 'The most beautiful commute I\'ve ever had.' },
  { category: 'Sparks & Musings', text: "I feel like people undersell Vancouver's [Specific Asset]." },
  { category: 'Sparks & Musings', text: 'I think [Tourist Spot] is actually overhyped because...' },
  { category: 'Sparks & Musings', text: 'If Vancouver were a colour, it would be...' },
  { category: 'Sparks & Musings', text: 'The one thing I would change about the city if I were Mayor for a day.' },
  { category: 'Sparks & Musings', text: 'The best bowl of [food] I\'ve had in the city.' },
  { category: 'Sparks & Musings', text: 'Vancouver rains a lot, but it makes [Place] look beautiful.' },
  { category: 'Sparks & Musings', text: 'The most "Vancouver" thing that has ever happened to me.' },
  { category: 'Sparks & Musings', text: 'My "Grey Sky" survival strategy.' },
  { category: 'Sparks & Musings', text: 'My relationship with the mountains is...' },
  { category: 'Sparks & Musings', text: 'My favourite place to go when I need to be completely alone.' },
  { category: 'Sparks & Musings', text: 'My favourite thrift find in a Vancouver shop.' },

]

export const PROMPT_CATEGORIES = [
  'Confessions',
  'Dear diary, today...',
  'Love & Romance',
  "A Visitor's Note",
  'Community Memories',
  'Arrivals & Departures',
  'Stranger Kindness',
  'Sparks & Musings',
]
